apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: web
  name: web
  namespace: {{ .Release.Namespace}}
spec:
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    - name: web-connection
      namespace: {{ .Release.Namespace }}
  forProvider:
    ami: {{ .Values.ami }}
    availabilityZone: {{ .Values.availabilityZone }}
    instanceType: {{ .Values.instanceType }}
    region: {{ .Values.region }}
    tags:
      {{- range $key, $value := .Values.tags }}
      {{ $key }}: {{ $value }}
      {{- end }}
    vpcSecurityGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
