apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIPAssociation
metadata:
  labels:
    testing.upbound.io/example-name: eip_assoc
  name: eip-assoc
spec:
  providerConfigRef:
    name: default
  forProvider:
    allocationIdSelector:
      matchLabels:
        testing.upbound.io/example-name: eip
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: web
    region: {{ .Values.region }}
