apiVersion: ec2.aws.upbound.io/v1beta1
kind: EIP
metadata:
  labels:
    testing.upbound.io/example-name: eip
  name: eip
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: {{ .Values.region }}
    vpc: true
