apiVersion: ec2.aws.upbound.io/v1beta1
kind: KeyPair
metadata:
  annotations:
    upjet.upbound.io/manual-intervention: Requires a valid public key.
  name: {{ .Values.keyPairName }}
spec:
  forProvider:
    publicKey: {{ .Files.Get "public.pem" | b64enc }}
    region: {{ .Values.region }}
