apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: s3/v1beta1/bucketaccelerateconfiguration
  labels:
    testing.upbound.io/example-name: example
  name: my-bucket
  namespace: {{ .Release.Namespace}}
spec:
  forProvider:
    region: {{ .Values.region }}
  providerConfigRef:
    name: default
  
