apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: instance-sg
  labels:
    testing.upbound.io/example-name: example
spec:
  forProvider:
    region: {{ .Values.region }}
    description: Testing security group
  providerConfigRef:
    name: example