on:
  push:
    branches:
      - main

permissions:
  checks: write
  contents: write
  statuses: write

jobs:
  template:
    name: Template the helm chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Helm tool installer
        uses: Azure/setup-helm@v1
        with:
          version: v3.11.2

      - name: Template the helm chart
        run: |
          helm lint ./ec2-instance

          if [ $? -eq 0 ]; then
            echo "Helm template succeeded"
          else
            echo "Helm template failed"
            exit 1
          fi
